---
title: "Diamonds In The Rough"
author: "John, Alec, Marcy, Rachel"
date: '2022-05-01'
output: html_document
---

# Question One

```{r, include = FALSE}
diamonds = read.csv("C:/Users/thing1/Documents/SCHOOL/4th_year/DS 301/DS301FinalProject/diamonds.csv",header=TRUE)
#most = subset(diamonds,select=-c(date))
#model = lm(total_sales_price~.,data=most)
#color = rgb(red=0,green=1, blue = 0, alpha=0.01)
#plot(model$residuals,model$fitted.values, col = color)

#?plot
```

Cleaning data
```{r}
diamonds = subset(diamonds,select= -c( diamond_id, date))
set.seed(1)



#### CLARITY ####
diamonds$clarity <- as.factor(diamonds$clarity)

#diamonds <- diamonds %>% filter(diamonds$clarity != "VS1")
#diamonds <- diamonds %>% filter(diamonds$clarity != "VS2")

new.levels<-c('below', 'below', 'below', 'above', 'below', 'below', 'below', 'below', 'above', 'above', 'above')
clarity <- factor(new.levels[diamonds$clarity])
diamonds$clarityBin <- as.factor(clarity)



#### CULET SIZE ####
diamonds$culet_size <- factor(diamonds$culet_size, levels=c("N","VS","S", "M", "SL", "L", "VL", "EL"))
new.levels<-c('None','small','small','large','large','large','large','large')

culet_size <-factor(new.levels[diamonds$culet_size])
culet_size_na <-addNA(culet_size)
levels(culet_size_na)<-c(levels(culet_size),"None")
diamonds$culet_size_bin<-as.factor(culet_size_na)

none <- sum(diamonds$culet_size_bin == 'none')
small <- sum(diamonds$culet_size_bin == 'small')
large <- sum(diamonds$culet_size_bin == "large")
rateSmall <- small / (length(diamonds$culet_size_bin))
rateLarge <- large / (length(diamonds$culet_size_bin))

#### COLOR ####
diamonds$color <- as.factor(diamonds$color)


#### CUT ####


diamonds$cut <- factor(diamonds$cut, levels=c("None", "Fair", "Good", "Very Good", "Excellent"))
new.levels<-c('None','below','below','above','above')

cut <-factor(new.levels[diamonds$cut])
cut_na <-addNA(cut)
levels(cut_na)<-c(levels(cut),"None")
diamonds$cut_bin<-as.factor(cut_na)

none <- sum(diamonds$cut_bin == 'None')
small <- sum(diamonds$cut_bin == 'above')
large <- sum(diamonds$cut_bin == "below")
rateNone <- none/(length(diamonds$cut_bin))
rateSmall <- small / (length(diamonds$cut_bin))
rateLarge <- large / (length(diamonds$cut_bin))


### POLISH ###
diamonds$polish <- factor(diamonds$polish, levels=c("Poor", "Fair", "Good", "Very Good", "Excellent"))
new.levels<-c('below','below','below','above','above')

polish <-factor(new.levels[diamonds$polish])
polish_na <-addNA(polish)
levels(polish_na)<-c(levels(polish),"None")
diamonds$polish_bin<-as.factor(polish_na)

none <- sum(diamonds$polish_bin == 'None')
small <- sum(diamonds$polish_bin == 'above')
large <- sum(diamonds$polish_bin == "below")
rateNone <- none/(length(diamonds$polish_bin))
rateSmall <- small / (length(diamonds$polish_bin))
rateLarge <- large / (length(diamonds$polish_bin))


#### SYMMETRY ####
diamonds$symmetry <- factor(diamonds$symmetry, levels=c("Poor", "Fair", "Good", "Very Good", "Excellent"))
new.levels<-c('below','below','below','above','above')

symmetry <-factor(new.levels[diamonds$symmetry])
symmetry_na <-addNA(symmetry)
levels(symmetry_na)<-c(levels(symmetry),"None")
diamonds$symmetry_bin<-as.factor(symmetry_na)

none <- sum(diamonds$symmetry_bin == 'None')
small <- sum(diamonds$symmetry_bin == 'above')
large <- sum(diamonds$symmetry_bin == "below")
rateNone <- none/(length(diamonds$symmetry_bin))
rateSmall <- small / (length(diamonds$symmetry_bin))
rateLarge <- large / (length(diamonds$symmetry_bin))

#### CULLET CONDITION ####
diamonds$culet_condition <- factor(diamonds$culet_condition, levels=c("Pointed", "Chipped", "Abraded"))
new.levels<-c('conditioned','conditioned','conditioned')

culet_condition <-factor(new.levels[diamonds$culet_condition])
culet_condition_na <-addNA(culet_condition)
levels(culet_condition_na)<-c(levels(culet_condition),"None")
diamonds$culet_condition_bin<-as.factor(culet_condition_na)

none <- sum(diamonds$culet_condition_bin == 'None')
small <- sum(diamonds$culet_condition_bin == 'conditioned')
rateNone <- none/(length(diamonds$culet_condition_bin))
rateSmall <- small / (length(diamonds$culet_condition_bin))

#### Fluor Color ####
diamonds$fluor_color <- factor(diamonds$fluor_color, levels=c("Blue", "Green", "Orange", "Yellow", "White"))
new.levels <-c("fluor_colored", "fluor_colored", "fluor_colored", "fluor_colored", "fluor_colored")
fluor_color <-factor(new.levels[diamonds$fluor_color])
fluor_color_na <-addNA(fluor_color)
levels(fluor_color_na)<-c(levels(fluor_color),"None")
diamonds$fluor_color_bin<-as.factor(fluor_color_na)

none <- sum(diamonds$fluor_color_bin == 'None')
small <- sum(diamonds$fluor_color_bin == 'fluor_colored')
rateNone <- none/(length(diamonds$fluor_color_bin))
rateSmall <- small / (length(diamonds$fluor_color_bin))

#### FLUOR INTENSITY ####
diamonds$fluor_intensity <- factor(diamonds$fluor_intensity, levels=c("None", "Faint", "Very Slight", "Slight", "Medium", "Strong", "Very Strong"))
new.levels <-c("None", "below", "below", "below", "above", "above","above")
fluor_intensity <-factor(new.levels[diamonds$fluor_intensity])
fluor_intensity_na <-addNA(fluor_intensity)
levels(fluor_intensity_na)<-c(levels(fluor_intensity),"None")
diamonds$fluor_intensity_bin<-as.factor(fluor_intensity_na)


none <- sum(diamonds$fluor_intensity_bin == 'None')
small <- sum(diamonds$fluor_intensity_bin == 'above')
large <- sum(diamonds$fluor_intensity_bin == "below")
rateNone <- none/(length(diamonds$fluor_intensity_bin))
rateSmall <- small / (length(diamonds$fluor_intensity_bin))
rateLarge <- large / (length(diamonds$fluor_intensity_bin))


#### GIRDLE MAX ####
diamonds$girdle_max <- factor(diamonds$girdle_max, levels=c("XTN", "VTN", "TN", "STN", "M", "STK", "TK", "VTK", "XTK"))
new.levels <-c("below", "below", "below", "below", "below", "above","above", "above", "above")
girdle_max <-factor(new.levels[diamonds$girdle_max])
girdle_max_na <-addNA(girdle_max)
levels(girdle_max_na)<-c(levels(girdle_max),"None")
diamonds$girdle_max_bin<-as.factor(girdle_max_na)

none <- sum(diamonds$girdle_max_bin == 'None')
small <- sum(diamonds$girdle_max_bin == 'below')
large <- sum(diamonds$girdle_max_bin == "above")
rateNone <- none/(length(diamonds$girdle_max_bin))
rateSmall <- small / (length(diamonds$girdle_max_bin))
rateLarge <- large / (length(diamonds$girdle_max_bin))


#### GIRDLE MIN ####
diamonds$girdle_min <- factor(diamonds$girdle_min, levels=c("XTN", "VTN", "TN", "STN", "M", "STK", "TK", "VTK", "XTK"))
new.levels <-c("below", "below", "below", "below", "below", "above","above", "above", "above")
girdle_min <-factor(new.levels[diamonds$girdle_min])
girdle_min_na <-addNA(girdle_min)
levels(girdle_min_na)<-c(levels(girdle_min),"None")
diamonds$girdle_min_bin<-as.factor(girdle_min_na)

none <- sum(diamonds$girdle_min_bin == 'None')
small <- sum(diamonds$girdle_min_bin == 'below')
large <- sum(diamonds$girdle_min_bin == "above")
rateNone <- none/(length(diamonds$girdle_min_bin))
rateSmall <- small / (length(diamonds$girdle_min_bin))
rateLarge <- large / (length(diamonds$girdle_min_bin))


#### EYE CLEAN ####
diamonds$eye_clean <- factor(diamonds$eye_clean, levels=c("No", "Borderline", "E1", "Yes"))
new.levels <-c("listed", "listed", "listed", "listed")
eye_clean <-factor(new.levels[diamonds$eye_clean])
eye_clean_na <-addNA(eye_clean)
levels(eye_clean_na)<-c(levels(eye_clean),"None")
diamonds$eye_clean_bin<-as.factor(eye_clean_na)

none <- sum(diamonds$eye_clean_bin == 'None')
listed <- sum(diamonds$eye_clean_bin == 'listed')
rateNone <- none/(length(diamonds$eye_clean_bin))
ratelisted <- listed / (length(diamonds$eye_clean_bin))

#### FANCY COLOR DOMINANT COLOR ####
diamonds$fancy_color_dominant_color <- factor(diamonds$fancy_color_dominant_color, levels=c("Black","Blue","Brown","Chameleon","Gray","Green","Orange","Other","Pink","Purple","Yellow"))
new.levels <-c("listed", "listed", "listed", "listed","listed","listed","listed","listed","listed","listed","listed" )
fancy_color_dominant_color <-factor(new.levels[diamonds$fancy_color_dominant_color])
fancy_color_dominant_color_na <-addNA(fancy_color_dominant_color)
levels(fancy_color_dominant_color_na)<-c(levels(fancy_color_dominant_color),"None")
diamonds$fancy_color_dominant_color_bin<-as.factor(fancy_color_dominant_color_na)

none <- sum(diamonds$fancy_color_dominant_color_bin == 'None')
listed <- sum(diamonds$fancy_color_dominant_color_bin == 'listed')
rateNone <- none/(length(diamonds$fancy_color_dominant_color_bin))
ratelisted <- listed / (length(diamonds$fancy_color_dominant_color_bin))




#### FANCY COLOR SECONDARY COLOR ####
diamonds$fancy_color_secondary_color <- factor(diamonds$fancy_color_secondary_color, levels=c("Blue","Brown","Gray","Green","Orange","Pink","Purple","Yellow"))
new.levels <-c("listed", "listed", "listed", "listed","listed","listed","listed","listed")
fancy_color_secondary_color <-factor(new.levels[diamonds$fancy_color_secondary_color])
fancy_color_secondary_color_na <-addNA(fancy_color_secondary_color)
levels(fancy_color_secondary_color_na)<-c(levels(fancy_color_secondary_color),"None")
diamonds$fancy_color_secondary_color_bin<-as.factor(fancy_color_secondary_color_na)

none <- sum(diamonds$fancy_color_secondary_color_bin == 'None')
listed <- sum(diamonds$fancy_color_secondary_color_bin == 'listed')
rateNone <- none/(length(diamonds$fancy_color_secondary_color_bin))
ratelisted <- listed / (length(diamonds$fancy_color_secondary_color_bin))




#### FANCY COLOR OVERTONE ####
diamonds$fancy_color_overtone <- factor(diamonds$fancy_color_overtone, levels=c("Brownish","Grayish","Greenish","None","Orangey","Pinkish","Purplish","Yellowish"))
new.levels <-c("listed", "listed", "listed", "listed","listed","listed","listed","listed")
fancy_color_overtone <-factor(new.levels[diamonds$fancy_color_overtone])
fancy_color_overtone_na <-addNA(fancy_color_overtone)
levels(fancy_color_overtone_na)<-c(levels(fancy_color_overtone),"None")
diamonds$fancy_color_overtone_bin<-as.factor(fancy_color_overtone_na)

none <- sum(diamonds$fancy_color_overtone_bin == 'None')
listed <- sum(diamonds$fancy_color_overtone_bin == 'listed')
rateNone <- none/(length(diamonds$fancy_color_overtone_bin))
ratelisted <- listed / (length(diamonds$fancy_color_overtone_bin))




#### Fancy Color Intensity ####
diamonds$fancy_color_intensity <- factor(diamonds$fancy_color_intensity, levels=c("Faint","Fancy","Fancy Dark","Fancy Deep","Fancy Intense","Fancy Light","Fancy Vivid","Light","Very Light"))
new.levels <-c("listed", "listed", "listed", "listed","listed","listed","listed","listed", "listed")
fancy_color_intensity <-factor(new.levels[diamonds$fancy_color_intensity])
fancy_color_intensity_na <-addNA(fancy_color_intensity)
levels(fancy_color_intensity_na)<-c(levels(fancy_color_intensity),"None")
diamonds$fancy_color_intensity_bin<-as.factor(fancy_color_intensity_na)

none <- sum(diamonds$fancy_color_intensity_bin == 'None')
listed <- sum(diamonds$fancy_color_intensity_bin == 'listed')
rateNone <- none/(length(diamonds$fancy_color_intensity_bin))
ratelisted <- listed / (length(diamonds$fancy_color_intensity_bin))


summary(diamonds$fancy_color_intensity_bin)


diamonds <- diamonds %>% filter(diamonds$total_sales_price < 10000)

diamonds_binned = subset(diamonds, select = c(clarityBin, size, color, cut_bin, total_sales_price, depth_percent, table_percent, meas_length, meas_width, meas_depth, fancy_color_overtone_bin, fancy_color_secondary_color_bin, girdle_min_bin,girdle_max_bin, culet_size_bin, culet_condition_bin, fluor_intensity_bin, fluor_color_bin, lab, eye_clean_bin, polish_bin,symmetry_bin))
```

MLR
```{r}
train = sample(1:nrow(diamonds_binned), nrow(diamonds_binned)*.7)
test=(-train)
train_data = diamonds_binned[train,]
test_data = diamonds_binned[-train,]



model = lm(total_sales_price ~., data=train_data)
summary(model)
MSE_train = mean((train_data$total_sales_price - model$fitted.values)^2) 
MSE_train


predicted_values = predict(model,test_data)
MSE_test = mean((test_data$total_sales_price - predicted_values)^2)
MSE_test
```


Regression

```{r}
## RIDGE

grid = 10^seq(10,-2,length=100)

x = model.matrix(total_sales_price ~.,data=diamonds_binned)[,-1]

Y = diamonds_binned$total_sales_price

ridge.train = glmnet(x[train,],Y[train],alpha=0,lambda=grid)
lasso.train = glmnet(x[train,],Y[train],alpha=1,lambda=grid)


cv.out.ridge = cv.glmnet(x[train,],Y[train],alpha = 0, lambda = grid) 
cv.out.lasso = cv.glmnet(x[train,],Y[train],alpha = 1, lambda = grid) 
bestlambdaridge = cv.out.ridge$lambda.min
bestlambdalasso = cv.out.lasso$lambda.min
selambdaridge = cv.out.ridge$lambda.1se
selambdalasso = cv.out.lasso$lambda.1se

ridge.pred1 = predict(cv.out.ridge,s=bestlambdaridge,newx=x[test,])
mean((ridge.pred1-Y[test])^2)
lasso.pred1 = predict(cv.out.lasso,s=bestlambdalasso,newx=x[test,])
mean((lasso.pred1-Y[test])^2)
ridge.pred2 = predict(cv.out.ridge,s=selambdaridge,newx=x[test,])
mean((ridge.pred2-Y[test])^2)
lasso.pred2 = predict(cv.out.lasso,s=selambdalasso,newx=x[test,])
mean((lasso.pred2-Y[test])^2)
bestlambdaridge
bestlambdalasso

grid
which(grid==bestlambdaridge)
cv.out.ridge$lambda[100]
coef(ridge.train)[,100]


```



#QUESTION TWO

####Split the clarity into two categories
```{r}
# REDOWNLOAD THE DATA SINCE IT'S CLEANED DIFFERENTLY

diamonds <- read.csv("/Users/alecrmeyer/Downloads/diamonds.csv", header=TRUE)

diamonds$clarity <- as.factor(diamonds$clarity)


new.levels<-c('below', 'below', 'below', 'above', 'below', 'below', 'below', 'below', 'above', 'above', 'above')
clarity <- factor(new.levels[diamonds$clarity])
diamonds$clarityBin <- as.factor(clarity)

diamonds = subset(diamonds,select= -c(clarity, diamond_id, date))

```

### Proportions
```{r}
above <- sum(diamonds$clarityBin == "above")

below <- sum(diamonds$clarityBin == "below")

rateAbove <- above / (above+below)
rateBelow <- below / (above+below)

```

Distance
```{r}
diamonds$culet_size <- factor(diamonds$culet_size, levels=c("N","VS","S", "M", "SL", "L", "VL", "EL"))
diamonds$color <- as.factor(diamonds$color)
diamonds$cut <- factor(diamonds$cut, levels=c("None", "Fair", "Good", "Very Good", "Excellent"))
diamonds$polish <- factor(diamonds$polish, levels=c("Poor", "Fair", "Good", "Very Good", "Excellent"))
diamonds$symmetry <- factor(diamonds$symmetry, levels=c("Poor", "Fair", "Good", "Very Good", "Excellent"))
diamonds$culet_condition <- factor(diamonds$culet_condition, levels=c("Pointed", "Chipped", "Abraded"))
diamonds$fluor_color <- factor(diamonds$fluor_color, levels=c("Blue", "Green", "Orange", "Yellow", "White"))
diamonds$fluor_color <- factor(diamonds$fluor_color, levels=c("None", "Faint", "Very Slight", "Slight", "Medium", "Strong", "Very Strong"))
diamonds$fluor_intensity <- factor(diamonds$fluor_intensity, levels=c("None", "Faint", "Very Slight", "Slight", "Medium", "Strong", "Very Strong"))
diamonds$girdle_max <- factor(diamonds$girdle_max, levels=c("XTN", "VTN", "TN", "STN", "M", "STK", "TK", "VTK", "XTK"))
diamonds$girdle_min <- factor(diamonds$girdle_min, levels=c("XTN", "VTN", "TN", "STN", "M", "STK", "TK", "VTK", "XTK"))
diamonds = subset(diamonds,select= -c(eye_clean))
diamonds = subset(diamonds,select= -c(lab))
diamonds = subset(diamonds,select= -c(fancy_color_dominant_color, fancy_color_secondary_color, fancy_color_overtone, fancy_color_intensity))

diamonds = subset(diamonds, select = c(clarityBin, color, cut, total_sales_price, depth_percent, table_percent, meas_length, meas_width, meas_depth))



diamonds$color <- as.numeric(diamonds$color)
diamonds$cut <- as.numeric(diamonds$cut)
diamonds$clarityBin <- as.numeric(diamonds$clarityBin)

diamonds <- na.omit(diamonds)




#diamonds$shape <- 


```

Random Forrest
```{r}
library(randomForest)

library(dplyr)

diamonds <- read.csv("/Users/alecrmeyer/Downloads/diamonds.csv", header=TRUE)

diamonds$clarity <- as.factor(diamonds$clarity)

diamonds <- diamonds %>% filter(diamonds$clarity != "VS1")
#diamonds <- diamonds %>% filter(diamonds$clarity != "VS2")

new.levels<-c('below', 'below', 'below', 'above', 'below', 'below', 'below', 'below', 'above', 'above', 'above')
clarity <- factor(new.levels[diamonds$clarity])
diamonds$clarityBin <- as.factor(clarity)

diamonds = subset(diamonds,select= -c(clarity, diamond_id, date))


train = sample(1:nrow(diamonds),nrow(diamonds)/2)
dim(diamonds)

diamonds$clarityBin <- as.factor(diamonds$clarityBin)

rf = randomForest(diamonds$clarityBin~.,data=diamonds, subset = train, mtry = 5, importance = TRUE, ntree=500)

rf.prob = predict(rf, newdata = diamonds[-train,]) 

tab.VS1 <- table(rf.prob, diamonds[-train,]$clarityBin)
misclass.VS1 <- 1-mean(rf.prob == diamonds[-train,]$clarityBin)



diamonds <- read.csv("/Users/alecrmeyer/Downloads/diamonds.csv", header=TRUE)

diamonds$clarity <- as.factor(diamonds$clarity)

#diamonds <- diamonds %>% filter(diamonds$clarity != "VS1")
diamonds <- diamonds %>% filter(diamonds$clarity != "VS2")

new.levels<-c('below', 'below', 'below', 'above', 'below', 'below', 'below', 'below', 'above', 'above', 'above')
clarity <- factor(new.levels[diamonds$clarity])
diamonds$clarityBin <- as.factor(clarity)

diamonds = subset(diamonds,select= -c(clarity, diamond_id, date))



train = sample(1:nrow(diamonds),nrow(diamonds)/2)
dim(diamonds)

diamonds$clarityBin <- as.factor(diamonds$clarityBin)

rf = randomForest(diamonds$clarityBin~.,data=diamonds, subset = train, mtry = 5, importance = TRUE, ntree=500)

rf.prob = predict(rf, newdata = diamonds[-train,]) 

tab.VS2 <- table(rf.prob, diamonds[-train,]$clarityBin)
misclass.VS2 <- 1-mean(rf.prob == diamonds[-train,]$clarityBin)



diamonds <- read.csv("/Users/alecrmeyer/Downloads/diamonds.csv", header=TRUE)

diamonds$clarity <- as.factor(diamonds$clarity)

diamonds <- diamonds %>% filter(diamonds$clarity != "VS1")
diamonds <- diamonds %>% filter(diamonds$clarity != "VS2")

new.levels<-c('below', 'below', 'below', 'above', 'below', 'below', 'below', 'below', 'above', 'above', 'above')
clarity <- factor(new.levels[diamonds$clarity])
diamonds$clarityBin <- as.factor(clarity)

diamonds = subset(diamonds,select= -c(clarity, diamond_id, date))



train = sample(1:nrow(diamonds),nrow(diamonds)/2)
dim(diamonds)

diamonds$clarityBin <- as.factor(diamonds$clarityBin)

rf = randomForest(diamonds$clarityBin~.,data=diamonds, subset = train, mtry = 5, importance = TRUE, ntree=500)

rf.prob = predict(rf, newdata = diamonds[-train,]) 

tab.both <- table(rf.prob, diamonds[-train,]$clarityBin)
misclass.both <- 1-mean(rf.prob == diamonds[-train,]$clarityBin)
```

```{r}
train = sample(1:nrow(diamonds),nrow(diamonds)/2)
dim(diamonds)

diamonds$clarityBin <- as.factor(diamonds$clarityBin)

rf = randomForest(diamonds$clarityBin~.,data=diamonds, subset = train, mtry = 5, importance = TRUE, ntree=500)

rf.prob = predict(rf, newdata = diamonds[-train,]) 

tab <- table(rf.prob, diamonds[-train,]$clarityBin)
misclass <- 1-mean(rf.prob == diamonds[-train,]$clarityBin)
```

Importance random forest
```{r}
diamonds = subset(diamonds, select = c(clarityBin, color, total_sales_price, depth_percent, table_percent, meas_length, meas_width, meas_depth, size))

train = sample(1:nrow(diamonds),nrow(diamonds)/2)
dim(diamonds)

diamonds$clarityBin <- as.factor(diamonds$clarityBin)

rf = randomForest(diamonds$clarityBin~.,data=diamonds, subset = train, mtry = 3, importance = TRUE, ntree=500)

rf.prob = predict(rf, newdata = diamonds[-train,]) 

tab <- table(rf.prob, diamonds[-train,]$clarityBin)
misclass <- 1-mean(rf.prob == diamonds[-train,]$clarityBin)
```

```{r}

tab <- table(rf.prob, diamonds[-train,]$clarityBin)
misclass <- 1-mean(rf.prob == diamonds[-train,]$clarityBin)

```

normalize total sales price
```{r}
diamonds <- diamonds %>% filter(diamonds$total_sales_price < 10000)
x <- qnorm(1-exp(-1/mean(diamonds$total_sales_price)*diamonds$total_sales_price))

```

knn CV
```{r}

train = sample(1:nrow(diamonds),nrow(diamonds)/2)

standardized.X = scale(diamonds[,-1])
training.y = diamonds$clarityBin[train]
training.x = standardized.X[train,] 

flds = createFolds(training.y, k = 10, list = TRUE, returnTrain = FALSE)

K = c(1, 3, 5, 7, 9, 11, 13)

cv_error = matrix(NA, 3, 7)

for(j in 1:7) {
  k = K[j]
  for(i in 1:3) {
    test_index = flds[[1]]
    testX = training.x[test_index, ]
    trainX = training.x[-test_index, ]
    
    trainY = training.y[-test_index]
    testY = training.y[test_index]
    
    knn.pred = knn(trainX, testX, trainY, k = k)
    cv_error[i, j] = mean(testY != knn.pred)
  }
}

apply(cv_error, 2, mean)


```

```{r}
mean_error <- apply(cv_error, 2, mean)
p <- cbind(K, mean_error)
plot(p)
```

KNN
```{r}
library(class)
library(caret)
train = sample(1:nrow(diamonds),nrow(diamonds)/2)

standardized.X = scale(diamonds[,-1])


training.y = diamonds$clarityBin[train]
training.x = diamonds[train, ] 
testing.x = diamonds[-train, ] 
testing.y = diamonds$clarityBin[-train]

knn.pred = knn(training.x, testing.x, training.y, k = 3)
table(knn.pred, testing.y)

misclass <- mean(testing.y != knn.pred)

```
